import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Provider } from '@/components/ui/provider'
import Header from '@/components/layouts/Header'
import Sidebar from '@/components/layouts/Sidebar'
import Invoice from '@/components/layouts/Invoice'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased overflow-hidden`}>
        <Provider>
          <div className="flex min-h-screen w-full">
            <Sidebar />
            <div className="w-full pl-[57px]">
              <Header />

              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  )
}
